docs_dir: docs/book
site_dir: docs/html
extra:
  project: Packages
  current_version: v1
  versions:
    - v1
nav:
  - Home: index.md
  - v1:
      - Overview: v1/overview.md
      - Installation: v1/installation.md
      - Configuration: v1/configuration.md
      - Usage: v1/usage.md
site_name: dot-data-fixtures
site_description: "DotKernel's CLI interface for interacting with doctrine/data-fixtures"
repo_url: "https://github.com/dotkernel/dot-data-fixtures"
plugins:
  - search
